name: Es-lint test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run es-lint command
        run: |
          npm i
          npm run lint